In [1]:
from immunodash.client import ChEMBLClient
from immunodash.targets import get_target

client = ChEMBLClient()

jak1 = get_target("JAK1")

activities = client.get_all(
    endpoint="activity",
    response_key="activities",
    params={
        "target_chembl_id": jak1["target_chembl_id"]
    }
)

In [2]:
import pandas as pd

df = pd.DataFrame(activities)

In [3]:
df.shape

(47757, 47)

In [4]:
df.dtypes

action_type                   object
activity_comment                 str
activity_id                    int64
activity_properties           object
assay_chembl_id                  str
assay_description                str
assay_type                       str
assay_variant_accession       object
assay_variant_mutation        object
bao_endpoint                     str
bao_format                       str
bao_label                        str
canonical_smiles                 str
data_validity_comment            str
data_validity_description        str
document_chembl_id               str
document_journal                 str
document_year                float64
ligand_efficiency             object
modality                      object
molecule_chembl_id               str
molecule_pref_name               str
parent_molecule_chembl_id        str
pchembl_value                    str
potential_duplicate            int64
qudt_units                       str
record_id                      int64
relation                         str
src_id                         int64
standard_flag                  int64
standard_relation                str
standard_text_value              str
standard_type                    str
standard_units                   str
standard_upper_value          object
standard_value                   str
target_chembl_id                 str
target_organism                  str
target_pref_name                 str
target_tax_id                    str
text_value                       str
toid                          object
type                             str
units                            str
uo_units                         str
upper_value                      str
value                            str
dtype: object

In [5]:
df.isna().sum().sort_values(ascending=False)

toid                         47757
standard_upper_value         47757
assay_variant_accession      47757
assay_variant_mutation       47757
modality                     47757
data_validity_description    47667
data_validity_comment        47667
text_value                   47655
standard_text_value          47655
upper_value                  47603
action_type                  46645
molecule_pref_name           45572
document_journal             42967
ligand_efficiency            32920
pchembl_value                32750
uo_units                     25815
qudt_units                   25815
value                        25805
standard_value               25805
standard_units               13054
activity_comment              5622
document_year                  738
units                          450
relation                       283
standard_relation              283
canonical_smiles               136
type                             0
activity_properties              0
activity_id                      0
target_tax_id                    0
target_pref_name                 0
target_organism                  0
target_chembl_id                 0
assay_chembl_id                  0
document_chembl_id               0
assay_description                0
standard_type                    0
standard_flag                    0
src_id                           0
record_id                        0
potential_duplicate              0
parent_molecule_chembl_id        0
bao_endpoint                     0
molecule_chembl_id               0
bao_format                       0
bao_label                        0
assay_type                       0
dtype: int64

In [6]:
df[[
    "standard_type",
    "standard_value",
    "standard_units",
    "pchembl_value",
    "standard_flag",
    "potential_duplicate"
]].head()

,standard_type,standard_value,standard_units,pchembl_value,standard_flag,potential_duplicate
0,IC50,10000.0,nM,NaN,1,0
1,IC50,39810.72,nM,4.40,1,0
2,IC50,19952.62,nM,4.70,1,0
3,Kd,NaN,NaN,NaN,0,0
4,Kd,NaN,NaN,NaN,0,0

In [7]:
df["standard_flag"].value_counts()

standard_flag
0    26442
1    21315
Name: count, dtype: int64

In [8]:
df["potential_duplicate"].value_counts()

potential_duplicate
0    43646
1     4111
Name: count, dtype: int64

In [9]:
df["standard_type"].value_counts()

standard_type
IC50                                    15034
kon                                     12761
k_off                                   12761
Ki                                       3890
Inhibition                               1429
Kd                                        582
EC50                                      443
Activity                                  218
% Control                                 216
Delta Tm                                  159
INH                                        49
% of control                               46
Ratio                                      44
% of inhibition                            26
FC                                         24
Ratio EC50                                 21
GI50                                       14
% inhibition                               12
Ratio IC50                                  5
% of engagement                             3
% residual kinase activity                  2
% Ctrl                                      2
DC50                                        2
Emax                                        2
% binding                                   2
ED50                                        2
Effect                                      2
Inihibition                                 1
% Residual activity with Skepinone-L        1
ECmax                                       1
GIC50                                       1
TIME                                        1
activity                                    1
Name: count, dtype: int64

In [13]:
df["standard_value"].map(type).value_counts()

standard_value
<class 'float'>    25805
<class 'str'>      21952
Name: count, dtype: int64

In [14]:
pd.to_numeric(df["standard_value"], errors="coerce")

0        10000.00
1        39810.72
2        19952.62
3             NaN
4             NaN
           ...
47752        9.00
47753      104.00
47754        0.00
47755        9.00
47756      104.00
Name: standard_value, Length: 47757, dtype: float64

In [15]:
df["standard_value"].isna().sum()

np.int64(25805)

In [16]:
pd.to_numeric(
    df["standard_value"],
    errors="coerce"
).isna().sum()

np.int64(25805)

In [17]:
(
    df.groupby("standard_type")["pchembl_value"]
      .apply(lambda x: x.notna().sum())
      .sort_values(ascending=False)
)

standard_type
IC50                                    11231
Ki                                       3237
EC50                                      404
Kd                                        133
ED50                                        2
INH                                         0
Inhibition                                  0
Inihibition                                 0
% Control                                   0
GI50                                        0
Ratio                                       0
Ratio EC50                                  0
Ratio IC50                                  0
TIME                                        0
activity                                    0
k_off                                       0
GIC50                                       0
Emax                                        0
FC                                          0
% Ctrl                                      0
Effect                                      0
ECmax                                       0
Delta Tm                                    0
DC50                                        0
Activity                                    0
% residual kinase activity                  0
% of inhibition                             0
% of engagement                             0
% of control                                0
% inhibition                                0
% binding                                   0
% Residual activity with Skepinone-L        0
kon                                         0
Name: pchembl_value, dtype: int64

In [18]:
(
    df.groupby(["standard_type", "standard_flag"])
      .size()
      .unstack(fill_value=0)
)

standard_flag                             0      1
standard_type
% Control                               216      0
% Ctrl                                    2      0
% Residual activity with Skepinone-L      1      0
% binding                                 2      0
% inhibition                             12      0
% of control                             46      0
% of engagement                           3      0
% of inhibition                          26      0
% residual kinase activity                2      0
Activity                                218      0
DC50                                      0      2
Delta Tm                                  0    159
EC50                                     16    427
ECmax                                     1      0
ED50                                      2      0
Effect                                    2      0
Emax                                      2      0
FC                                       24      0
GI50                                      0     14
GIC50                                     1      0
IC50                                    120  14914
INH                                      49      0
Inhibition                               84   1345
Inihibition                               1      0
Kd                                       19    563
Ki                                        0   3890
Ratio                                    44      0
Ratio EC50                               21      0
Ratio IC50                                5      0
TIME                                      0      1
activity                                  1      0
k_off                                 12761      0
kon                                   12761      0